### ISSUE TITLE
make with error

### ISSUE THREAD

**Issue by benny-wangaimin** [storm-cm/storm-csd#1]
when I make and got some error,would u please help me.
[INFO] ------------------------------------------------------------------------
groovy extract_config.groovy < storm/storm-core/src/jvm/backtype/storm/Config.java > descriptor/service.sdl
Caught: groovy.lang.MissingMethodException: No signature of method: groovy.json.JsonSlurper.parse() is applicable for argument types: (java.io.File) values: [descriptor/service.sdl.in]
Possible solutions: parse(java.io.Reader), use([Ljava.lang.Object;), wait(), grep(), any(), wait(long)
groovy.lang.MissingMethodException: No signature of method: groovy.json.JsonSlurper.parse() is applicable for argument types: (java.io.File) values: [descriptor/service.sdl.in]
Possible solutions: parse(java.io.Reader), use([Ljava.lang.Object;), wait(), grep(), any(), wait(long)
        at extract_config.run(extract_config.groovy:185)
make: **\* [descriptor/service.sdl] Error 1

The whole make output info:
solway@hadoop1:~/storm-csd-master$ make clean
rm -rf stamp-\* *.jar *.tmp aux/storm.yaml aux/storm.yaml.tmp cm_ext storm
solway@hadoop1:~/storm-csd-master$ make
git clone -b v0.9.5 https://github.com/apache/storm
Cloning into 'storm'...
remote: Counting objects: 74583, done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 74583 (delta 1), reused 0 (delta 0), pack-reused 74574
Receiving objects: 100% (74583/74583), 148.16 MiB | 564.00 KiB/s, done.
Resolving deltas: 100% (38378/38378), done.
Checking connectivity... done.
Note: checking out 'c9c47b36071c02488ee1e75eb3851e58191b7534'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

touch stamp-storm
git clone https://github.com/cloudera/cm_ext.git
Cloning into 'cm_ext'...
remote: Counting objects: 1291, done.
remote: Total 1291 (delta 0), reused 0 (delta 0), pack-reused 1291
Receiving objects: 100% (1291/1291), 706.83 KiB | 142.00 KiB/s, done.
Resolving deltas: 100% (650/650), done.
Checking connectivity... done.
touch stamp-cm_ext
cd cm_ext && mvn -pl validator package
[INFO] Scanning for projects...
[INFO]  
[INFO] ------------------------------------------------------------------------
[INFO] Building Schema Validator 5.4.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.3:resources (default-resources) @ schema-validator ---
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ schema-validator ---
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 6 source files to /home/solway/storm-csd-master/cm_ext/validator/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:2.3:testResources (default-testResources) @ schema-validator ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 23 resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:testCompile (default-testCompile) @ schema-validator ---
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 1 source file to /home/solway/storm-csd-master/cm_ext/validator/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ schema-validator ---
[INFO] Surefire report directory: /home/solway/storm-csd-master/cm_ext/validator/target/surefire-reports

---
##  T E S T S

Running com.cloudera.cli.validator.MainTest
Tests run: 24, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 18.313 sec

Results :

Tests run: 24, Failures: 0, Errors: 0, Skipped: 0

[INFO] 
[INFO] --- maven-jar-plugin:2.3.1:jar (default-jar) @ schema-validator ---
[INFO] Building jar: /home/solway/storm-csd-master/cm_ext/validator/target/schema-validator-5.4.0.jar
[INFO] 
[INFO] --- maven-jar-plugin:2.3.1:test-jar (default) @ schema-validator ---
[INFO] Building jar: /home/solway/storm-csd-master/cm_ext/validator/target/schema-validator-5.4.0-tests.jar
[INFO] 
[INFO] --- maven-assembly-plugin:2.3:single (assemble-all) @ schema-validator ---
[INFO] META-INF/MANIFEST.MF already added, skipping
[INFO] META-INF/MANIFEST.MF already added, skipping
[INFO] META-INF/MANIFEST.MF already added, skipping
[INFO] META-INF/MANIFEST.MF already added, skipping
[INFO] META-INF/MANIFEST.MF already added, skipping
[INFO] META-INF/MANIFEST.MF already added, skipping
[INFO] META-INF/MANIFEST.MF already added, skipping
[INFO] META-INF/MANIFEST.MF already added, skipping
[INFO] META-INF/MANIFEST.MF already added, skipping
[INFO] META-INF/MANIFEST.MF already added, skipping
[INFO] META-INF/MANIFEST.MF already added, skipping
[INFO] META-INF/MANIFEST.MF already added, skipping
[INFO] META-INF/LICENSE.txt already added, skipping
[INFO] META-INF/MANIFEST.MF already added, skipping
[INFO] META-INF/MANIFEST.MF already added, skipping
[INFO] META-INF/LICENSE.txt already added, skipping
[INFO] META-INF/NOTICE.txt already added, skipping
[INFO] META-INF/MANIFEST.MF already added, skipping
[INFO] META-INF/MANIFEST.MF already added, skipping
[INFO] META-INF/LICENSE.txt already added, skipping
[INFO] META-INF/NOTICE.txt already added, skipping
[INFO] META-INF/MANIFEST.MF already added, skipping
[INFO] META-INF/LICENSE.txt already added, skipping
[INFO] META-INF/NOTICE.txt already added, skipping
[INFO] META-INF/MANIFEST.MF already added, skipping
[INFO] META-INF/LICENSE.txt already added, skipping
[INFO] META-INF/NOTICE.txt already added, skipping
[INFO] META-INF/MANIFEST.MF already added, skipping
[INFO] META-INF/LICENSE.txt already added, skipping
[INFO] META-INF/NOTICE.txt already added, skipping
[INFO] META-INF/MANIFEST.MF already added, skipping
[INFO] META-INF/LICENSE.txt already added, skipping
[INFO] META-INF/NOTICE.txt already added, skipping
[INFO] META-INF/MANIFEST.MF already added, skipping
[INFO] META-INF/LICENSE already added, skipping
[INFO] META-INF/NOTICE already added, skipping
[INFO] META-INF/MANIFEST.MF already added, skipping
[INFO] META-INF/MANIFEST.MF already added, skipping
[INFO] META-INF/MANIFEST.MF already added, skipping
[INFO] META-INF/MANIFEST.MF already added, skipping
[INFO] META-INF/spring.handlers already added, skipping
[INFO] META-INF/spring.schemas already added, skipping
[INFO] META-INF/spring.tooling already added, skipping
[INFO] META-INF/notice.txt already added, skipping
[INFO] META-INF/license.txt already added, skipping
[INFO] META-INF/MANIFEST.MF already added, skipping
[INFO] META-INF/MANIFEST.MF already added, skipping
[INFO] META-INF/spring.handlers already added, skipping
[INFO] META-INF/spring.schemas already added, skipping
[INFO] META-INF/spring.tooling already added, skipping
[INFO] META-INF/notice.txt already added, skipping
[INFO] META-INF/license.txt already added, skipping
[INFO] META-INF/MANIFEST.MF already added, skipping
[INFO] META-INF/notice.txt already added, skipping
[INFO] META-INF/license.txt already added, skipping
[INFO] META-INF/MANIFEST.MF already added, skipping
[INFO] META-INF/notice.txt already added, skipping
[INFO] META-INF/license.txt already added, skipping
[INFO] META-INF/MANIFEST.MF already added, skipping
[INFO] META-INF/MANIFEST.MF already added, skipping
[INFO] META-INF/MANIFEST.MF already added, skipping
[INFO] META-INF/LICENSE.txt already added, skipping
[INFO] META-INF/NOTICE.txt already added, skipping
[INFO] META-INF/MANIFEST.MF already added, skipping
[INFO] META-INF/MANIFEST.MF already added, skipping
[INFO] Building jar: /home/solway/storm-csd-master/cm_ext/validator/target/validator.jar
[INFO] META-INF/MANIFEST.MF already added, skipping
[INFO] META-INF/MANIFEST.MF already added, skipping
[INFO] META-INF/MANIFEST.MF already added, skipping
[INFO] META-INF/MANIFEST.MF already added, skipping
[INFO] META-INF/MANIFEST.MF already added, skipping
[INFO] META-INF/MANIFEST.MF already added, skipping
[INFO] META-INF/MANIFEST.MF already added, skipping
[INFO] META-INF/MANIFEST.MF already added, skipping
[INFO] META-INF/MANIFEST.MF already added, skipping
[INFO] META-INF/MANIFEST.MF already added, skipping
[INFO] META-INF/MANIFEST.MF already added, skipping
[INFO] META-INF/MANIFEST.MF already added, skipping
[INFO] META-INF/LICENSE.txt already added, skipping
[INFO] META-INF/MANIFEST.MF already added, skipping
[INFO] META-INF/MANIFEST.MF already added, skipping
[INFO] META-INF/LICENSE.txt already added, skipping
[INFO] META-INF/NOTICE.txt already added, skipping
[INFO] META-INF/MANIFEST.MF already added, skipping
[INFO] META-INF/MANIFEST.MF already added, skipping
[INFO] META-INF/LICENSE.txt already added, skipping
[INFO] META-INF/NOTICE.txt already added, skipping
[INFO] META-INF/MANIFEST.MF already added, skipping
[INFO] META-INF/LICENSE.txt already added, skipping
[INFO] META-INF/NOTICE.txt already added, skipping
[INFO] META-INF/MANIFEST.MF already added, skipping
[INFO] META-INF/LICENSE.txt already added, skipping
[INFO] META-INF/NOTICE.txt already added, skipping
[INFO] META-INF/MANIFEST.MF already added, skipping
[INFO] META-INF/LICENSE.txt already added, skipping
[INFO] META-INF/NOTICE.txt already added, skipping
[INFO] META-INF/MANIFEST.MF already added, skipping
[INFO] META-INF/LICENSE.txt already added, skipping
[INFO] META-INF/NOTICE.txt already added, skipping
[INFO] META-INF/MANIFEST.MF already added, skipping
[INFO] META-INF/LICENSE already added, skipping
[INFO] META-INF/NOTICE already added, skipping
[INFO] META-INF/MANIFEST.MF already added, skipping
[INFO] META-INF/MANIFEST.MF already added, skipping
[INFO] META-INF/MANIFEST.MF already added, skipping
[INFO] META-INF/MANIFEST.MF already added, skipping
[INFO] META-INF/spring.handlers already added, skipping
[INFO] META-INF/spring.schemas already added, skipping
[INFO] META-INF/spring.tooling already added, skipping
[INFO] META-INF/notice.txt already added, skipping
[INFO] META-INF/license.txt already added, skipping
[INFO] META-INF/MANIFEST.MF already added, skipping
[INFO] META-INF/MANIFEST.MF already added, skipping
[INFO] META-INF/spring.handlers already added, skipping
[INFO] META-INF/spring.schemas already added, skipping
[INFO] META-INF/spring.tooling already added, skipping
[INFO] META-INF/notice.txt already added, skipping
[INFO] META-INF/license.txt already added, skipping
[INFO] META-INF/MANIFEST.MF already added, skipping
[INFO] META-INF/notice.txt already added, skipping
[INFO] META-INF/license.txt already added, skipping
[INFO] META-INF/MANIFEST.MF already added, skipping
[INFO] META-INF/notice.txt already added, skipping
[INFO] META-INF/license.txt already added, skipping
[INFO] META-INF/MANIFEST.MF already added, skipping
[INFO] META-INF/MANIFEST.MF already added, skipping
[INFO] META-INF/MANIFEST.MF already added, skipping
[INFO] META-INF/LICENSE.txt already added, skipping
[INFO] META-INF/NOTICE.txt already added, skipping
[INFO] META-INF/MANIFEST.MF already added, skipping
[INFO] META-INF/MANIFEST.MF already added, skipping
[WARNING] Configuration options: 'appendAssemblyId' is set to false, and 'classifier' is missing.
Instead of attaching the assembly file: /home/solway/storm-csd-master/cm_ext/validator/target/validator.jar, it will become the file for main project artifact.
NOTE: If multiple descriptors or descriptor-formats are provided for this project, the value of this file will be non-deterministic!
[WARNING] Replacing pre-existing project main-artifact file: /home/solway/storm-csd-master/cm_ext/validator/target/schema-validator-5.4.0.jar
with assembly file: /home/solway/storm-csd-master/cm_ext/validator/target/validator.jar
[INFO] 
[INFO] --- maven-javadoc-plugin:2.9:jar (attach-javadocs) @ schema-validator ---
[WARNING] Source files encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] 
Loading source files for package com.cloudera.cli.validator...
Loading source files for package com.cloudera.cli.validator.components...
Constructing Javadoc information...
Standard Doclet version 1.7.0_67
Building tree for all the packages and classes...
Generating /home/solway/storm-csd-master/cm_ext/validator/target/javadoc/com/cloudera/cli/validator/ApplicationConfiguration.html...
Generating /home/solway/storm-csd-master/cm_ext/validator/target/javadoc/com/cloudera/cli/validator/Main.html...
Generating /home/solway/storm-csd-master/cm_ext/validator/target/javadoc/com/cloudera/cli/validator/components/CommandLineOptions.html...
Generating /home/solway/storm-csd-master/cm_ext/validator/target/javadoc/com/cloudera/cli/validator/components/CommandLineOptions.Mode.html...
Generating /home/solway/storm-csd-master/cm_ext/validator/target/javadoc/com/cloudera/cli/validator/components/Constants.html...
Generating /home/solway/storm-csd-master/cm_ext/validator/target/javadoc/com/cloudera/cli/validator/components/ParcelDirectoryRunner.html...
Generating /home/solway/storm-csd-master/cm_ext/validator/target/javadoc/com/cloudera/cli/validator/components/ParcelFileRunner.html...
Generating /home/solway/storm-csd-master/cm_ext/validator/target/javadoc/overview-frame.html...
Generating /home/solway/storm-csd-master/cm_ext/validator/target/javadoc/com/cloudera/cli/validator/package-frame.html...
Generating /home/solway/storm-csd-master/cm_ext/validator/target/javadoc/com/cloudera/cli/validator/package-summary.html...
Generating /home/solway/storm-csd-master/cm_ext/validator/target/javadoc/com/cloudera/cli/validator/package-tree.html...
Generating /home/solway/storm-csd-master/cm_ext/validator/target/javadoc/com/cloudera/cli/validator/components/package-frame.html...
Generating /home/solway/storm-csd-master/cm_ext/validator/target/javadoc/com/cloudera/cli/validator/components/package-summary.html...
Generating /home/solway/storm-csd-master/cm_ext/validator/target/javadoc/com/cloudera/cli/validator/components/package-tree.html...
Generating /home/solway/storm-csd-master/cm_ext/validator/target/javadoc/constant-values.html...
Copying file /home/solway/storm-csd-master/cm_ext/validator/src/javadoc/javadoc.css to file /home/solway/storm-csd-master/cm_ext/validator/target/javadoc/javadoc.css...
Generating /home/solway/storm-csd-master/cm_ext/validator/target/javadoc/com/cloudera/cli/validator/class-use/ApplicationConfiguration.html...
Generating /home/solway/storm-csd-master/cm_ext/validator/target/javadoc/com/cloudera/cli/validator/class-use/Main.html...
Generating /home/solway/storm-csd-master/cm_ext/validator/target/javadoc/com/cloudera/cli/validator/components/class-use/Constants.html...
Generating /home/solway/storm-csd-master/cm_ext/validator/target/javadoc/com/cloudera/cli/validator/components/class-use/ParcelDirectoryRunner.html...
Generating /home/solway/storm-csd-master/cm_ext/validator/target/javadoc/com/cloudera/cli/validator/components/class-use/CommandLineOptions.html...
Generating /home/solway/storm-csd-master/cm_ext/validator/target/javadoc/com/cloudera/cli/validator/components/class-use/CommandLineOptions.Mode.html...
Generating /home/solway/storm-csd-master/cm_ext/validator/target/javadoc/com/cloudera/cli/validator/components/class-use/ParcelFileRunner.html...
Generating /home/solway/storm-csd-master/cm_ext/validator/target/javadoc/com/cloudera/cli/validator/package-use.html...
Generating /home/solway/storm-csd-master/cm_ext/validator/target/javadoc/com/cloudera/cli/validator/components/package-use.html...
Building index for all the packages and classes...
Generating /home/solway/storm-csd-master/cm_ext/validator/target/javadoc/overview-tree.html...
Generating /home/solway/storm-csd-master/cm_ext/validator/target/javadoc/index-all.html...
Generating /home/solway/storm-csd-master/cm_ext/validator/target/javadoc/deprecated-list.html...
Building index for all classes...
Generating /home/solway/storm-csd-master/cm_ext/validator/target/javadoc/allclasses-frame.html...
Generating /home/solway/storm-csd-master/cm_ext/validator/target/javadoc/allclasses-noframe.html...
Generating /home/solway/storm-csd-master/cm_ext/validator/target/javadoc/index.html...
Generating /home/solway/storm-csd-master/cm_ext/validator/target/javadoc/overview-summary.html...
Generating /home/solway/storm-csd-master/cm_ext/validator/target/javadoc/help-doc.html...
1 warning
[WARNING] Javadoc Warnings
[WARNING] /home/solway/storm-csd-master/cm_ext/validator/src/main/java/com/cloudera/cli/validator/components/ParcelDirectoryRunner.java:44: warning - Tag @link: can't find ValidationRunner in com.cloudera.cli.validator.components.ParcelDirectoryRunner
[INFO] Building jar: /home/solway/storm-csd-master/cm_ext/validator/target/schema-validator-5.4.0-javadoc.jar
[INFO] 
[INFO] >>> maven-source-plugin:2.2.1:jar (attach-sources) @ schema-validator >>>
[INFO] 
[INFO] <<< maven-source-plugin:2.2.1:jar (attach-sources) @ schema-validator <<<
[INFO] 
[INFO] --- maven-source-plugin:2.2.1:jar (attach-sources) @ schema-validator ---
[INFO] Building jar: /home/solway/storm-csd-master/cm_ext/validator/target/schema-validator-5.4.0-sources.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 56.419s
[INFO] Finished at: Fri Dec 04 11:36:19 CST 2015
[INFO] Final Memory: 29M/242M
[INFO] ------------------------------------------------------------------------
groovy extract_config.groovy < storm/storm-core/src/jvm/backtype/storm/Config.java > descriptor/service.sdl
Caught: groovy.lang.MissingMethodException: No signature of method: groovy.json.JsonSlurper.parse() is applicable for argument types: (java.io.File) values: [descriptor/service.sdl.in]
Possible solutions: parse(java.io.Reader), use([Ljava.lang.Object;), wait(), grep(), any(), wait(long)
groovy.lang.MissingMethodException: No signature of method: groovy.json.JsonSlurper.parse() is applicable for argument types: (java.io.File) values: [descriptor/service.sdl.in]
Possible solutions: parse(java.io.Reader), use([Ljava.lang.Object;), wait(), grep(), any(), wait(long)
        at extract_config.run(extract_config.groovy:185)
make: **\* [descriptor/service.sdl] Error 1
solway@hadoop1:~/storm-csd-master$

**Comment by benny-wangaimin** [comment]
I use new groovy 2.4.5 version and make can pass.

**Comment by benny-wangaimin** [comment]
Now I can manage storm under CDH cm to deploy,start,stop service related storm.
Thank your very much for your contribution.
